CREATE TABLE "markets" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "markets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"market_id" integer NOT NULL,
	"creator" varchar(42) NOT NULL,
	"starts_at" numeric(20, 0) NOT NULL,
	"expires_at" numeric(20, 0) NOT NULL,
	"collateral_token" varchar(42) NOT NULL,
	"outcome_count" integer NOT NULL,
	"initial_collateral" numeric(20, 0) NOT NULL,
	"creator_fee_bps" integer NOT NULL,
	"meta_data_uri" text,
	"alpha" numeric(20, 0) NOT NULL,
	"title" text,
	"resolution_criteria" text,
	"end_date" numeric(20, 0),
	"outcomes" json,
	"total_volume" numeric(20, 0) DEFAULT '0' NOT NULL,
	"trade_count" integer DEFAULT 0 NOT NULL,
	"resolved" boolean DEFAULT false NOT NULL,
	"resolved_at" timestamp,
	"chain_data_updated_at" timestamp,
	"needs_chain_update" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "markets_market_id_unique" UNIQUE("market_id")
);
